language: python
python:
  - "2.7"
env:
  - DJANGO=1.6 DB=postgres
services:
  - rabbitmq
  - memcached
branches:
  only:
    - develop
    - master
cache:
  directories:
    - ~/virtualenv/python2.7/
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database foo;' -U postgres
  - cp oauth2server/proj/settings/local.example.py oauth2server/proj/settings/local.py
  - cd oauth2server
  - python manage.py syncdb --noinput
script:
  - python manage.py test